# Generated by Django 5.2.7 on 2025-10-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idv', models.FloatField()),
                ('rate', models.FloatField()),
                ('sAdd', models.FloatField()),
                ('odPremium', models.FloatField()),
                ('odMinusNCB', models.FloatField()),
                ('ncb', models.IntegerField()),
                ('discount', models.FloatField()),
                ('netPremium', models.FloatField()),
                ('legalLiability', models.FloatField()),
                ('seatingCapacity', models.IntegerField()),
                ('tpPremium', models.FloatField()),
                ('totalPremium', models.FloatField()),
                ('po', models.FloatField()),
                ('poAmount', models.FloatField()),
                ('payableAmount', models.FloatField()),
                ('regYear', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('dueDate', models.DateField()),
                ('policyType', models.CharField(max_length=100)),
            ],
        ),
    ]
