# Generated by Django 5.2.7 on 2025-10-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='regno',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='calculation',
            name='year',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
