# Generated by Django 5.2.7 on 2025-10-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0002_calculation_regno_calculation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='poAmoun',
            field=models.FloatField(default=0.0),
        ),
    ]
