# Generated by Django 5.2.7 on 2025-10-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0003_calculation_poamoun'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idv', models.FloatField()),
                ('rate', models.FloatField()),
                ('sAdd', models.FloatField()),
                ('odPremium', models.FloatField()),
                ('odMinusNCB', models.FloatField()),
                ('ncb', models.IntegerField()),
                ('discount', models.FloatField()),
                ('netPremium', models.FloatField()),
                ('legalLiability', models.FloatField()),
                ('seatingCapacity', models.IntegerField()),
                ('tpPremium', models.FloatField()),
                ('totalPremium', models.FloatField()),
                ('po', models.FloatField()),
                ('poAmount', models.FloatField()),
                ('payableAmount', models.FloatField()),
                ('regYear', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('dueDate', models.DateField()),
                ('policyType', models.CharField(max_length=100)),
                ('regno', models.CharField(default='0', max_length=20)),
                ('year', models.DateField(default='2000-01-01')),
                ('poAmoun', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
