# Generated by Django 5.2.7 on 2025-10-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0004_calculationnew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationnew',
            name='poAmoun',
        ),
        migrations.AlterField(
            model_name='calculationnew',
            name='netPremium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculationnew',
            name='odMinusNCB',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculationnew',
            name='odPremium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculationnew',
            name='payableAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculationnew',
            name='po',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='calculationnew',
            name='poAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculationnew',
            name='totalPremium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculationnew',
            name='tpPremium',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
