# Generated by Django 5.2.7 on 2025-10-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0005_remove_calculationnew_poamoun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=100)),
                ('restrictions', models.JSONField(default=list)),
                ('extra_charges', models.FloatField()),
            ],
        ),
    ]
