# Generated by Django 5.2.7 on 2025-10-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0006_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationnew',
            name='institute',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
