# Generated by Django 5.2.7 on 2025-10-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0007_calculationnew_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationnew',
            name='institute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
