# Generated by Django 5.2.7 on 2025-10-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0008_alter_calculationnew_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalCalculationNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idv', models.FloatField()),
                ('rate', models.FloatField()),
                ('sAdd', models.FloatField()),
                ('odPremium', models.FloatField(blank=True, null=True)),
                ('odMinusNCB', models.FloatField(blank=True, null=True)),
                ('ncb', models.IntegerField()),
                ('discount', models.FloatField()),
                ('netPremium', models.FloatField(blank=True, null=True)),
                ('legalLiability', models.FloatField()),
                ('seatingCapacity', models.IntegerField()),
                ('tpPremium', models.FloatField(blank=True, null=True)),
                ('totalPremium', models.FloatField(blank=True, null=True)),
                ('po', models.FloatField(default=0.0)),
                ('poAmount', models.FloatField(blank=True, null=True)),
                ('payableAmount', models.FloatField(blank=True, null=True)),
                ('regYear', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('dueDate', models.DateField()),
                ('policyType', models.CharField(max_length=100)),
                ('regno', models.CharField(default='0', max_length=20)),
                ('year', models.DateField(default='2000-01-01')),
                ('institute', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='calculationnew',
            name='institute',
        ),
    ]
