# Generated by Django 5.2.7 on 2025-10-30 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0009_finalcalculationnew_remove_calculationnew_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcalculationnew',
            name='company',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='calculations.company'),
        ),
    ]
