# Generated by Django 5.2.7 on 2025-10-31 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0010_alter_finalcalculationnew_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculationNew',
        ),
    ]
