# Generated by Django 5.2.7 on 2025-11-04 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0012_calculationnew_delete_finalcalculationnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companydetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=100)),
                ('restrictions', models.JSONField(default=list)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('extra_charges', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CalculationNewForDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idvnew', models.FloatField()),
                ('ratenew', models.FloatField()),
                ('sAddnew', models.FloatField()),
                ('odPremiumnew', models.FloatField(blank=True, null=True)),
                ('odMinusNCBnew', models.FloatField(blank=True, null=True)),
                ('ncbnew', models.IntegerField()),
                ('discountnew', models.FloatField()),
                ('netPremiumnew', models.FloatField(blank=True, null=True)),
                ('legalLiabilitynew', models.FloatField()),
                ('seatingCapacitynew', models.IntegerField()),
                ('tpPremiumnew', models.FloatField(blank=True, null=True)),
                ('totalPremiumnew', models.FloatField(blank=True, null=True)),
                ('ponew', models.FloatField(default=0.0)),
                ('poAmountnew', models.FloatField(blank=True, null=True)),
                ('payableAmountnew', models.FloatField(blank=True, null=True)),
                ('regYearnew', models.IntegerField()),
                ('dueDatenew', models.DateField()),
                ('policyTypenew', models.CharField(max_length=100)),
                ('regnonew', models.CharField(default='0', max_length=20)),
                ('yearnew', models.DateField(default='2000-01-01')),
                ('institutenew', models.CharField(blank=True, max_length=100, null=True)),
                ('created_atnew', models.DateTimeField(auto_now_add=True)),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculations.companydetails')),
            ],
        ),
    ]
