# Generated by Django 5.2.7 on 2025-11-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0013_companydetails_calculationnewfordrop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationnewfordrop',
            name='created_atnew',
        ),
        migrations.RemoveField(
            model_name='calculationnewfordrop',
            name='discountnew',
        ),
        migrations.RemoveField(
            model_name='calculationnewfordrop',
            name='dueDatenew',
        ),
        migrations.RemoveField(
            model_name='calculationnewfordrop',
            name='institutenew',
        ),
        migrations.RemoveField(
            model_name='calculationnewfordrop',
            name='legalLiabilitynew',
        ),
        migrations.RemoveField(
            model_name='calculationnewfordrop',
            name='ncbnew',
        ),
        migrations.RemoveField(
            model_name='calculationnewfordrop',
            name='netPremiumnew',
        ),
        migrations.RemoveField(
            model_name='calculationnewfordrop',
            name='odMinusNCBnew',
        ),
        migrations.RemoveField(
            model_name='calculationnewfordrop',
            name='payableAmountnew',
        ),
        migrations.RemoveField(
            model_name='calculationnewfordrop',
            name='poAmountnew',
        ),
        migrations.RemoveField(
            model_name='calculationnewfordrop',
            name='policyTypenew',
        ),
        migrations.RemoveField(
            model_name='calculationnewfordrop',
            name='ponew',
        ),
        migrations.RemoveField(
            model_name='calculationnewfordrop',
            name='regYearnew',
        ),
        migrations.RemoveField(
            model_name='calculationnewfordrop',
            name='regnonew',
        ),
        migrations.RemoveField(
            model_name='calculationnewfordrop',
            name='seatingCapacitynew',
        ),
        migrations.RemoveField(
            model_name='calculationnewfordrop',
            name='totalPremiumnew',
        ),
        migrations.RemoveField(
            model_name='calculationnewfordrop',
            name='tpPremiumnew',
        ),
        migrations.RemoveField(
            model_name='calculationnewfordrop',
            name='yearnew',
        ),
    ]
