# Generated by Django 5.2.7 on 2025-11-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0014_remove_calculationnewfordrop_created_atnew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='restrictions',
            field=models.CharField(default=list),
        ),
    ]
